uizaio/api-wrapper-go

- client/client.go
- cmd/main.go
- entity.go
- entity/client.go
- error.go
- form/form.go
- params.go
- testing/testing.go
- uiza.go
> [Phase 1][Sprint 1] Init project and add Entity Retrieve

- client/client.go
- cmd/main.go
- entity.go
- entity/client.go
- error.go
- form/form.go
- params.go
- testing/testing.go
- uiza.go
> Init project and add Entity Retrieve

- .vscode/launch.json
- entity.go
- entity/client.go
- entity/client_test.go
- entity/validate.go
- testing/testing.go
> Implement Create Entity

- README.md
- cmd/main.go
- entity/client.go
- testing/testing.go
- uiza.go
- General Readme
- Document for : Entity Create and Retrieve
- Comment, remove some trash code
> [Phase 1 Sprint 1] Add Readme, comment and remove some trash code

- entity.go
- entity/client.go
https://dev.framgia.com/issues/221757
https://dev.framgia.com/issues/221761
> [#221757] [#221761] - [Go][Entity][Publish to CDN] Coding

- docs/Entity.md
- entity.go
- entity/client.go
- iter.go
https://dev.framgia.com/issues/221739
> [#221739][Task][Entity][List]: Coding

- entity.go
- entity/client.go
- Fix response từ string thành object hàm Retrieve, Create
> [#222966] - [Go][Entity] [Get AWS upload key] Coding

- docs/Entity.md
- entity.go
- entity/client.go
> Implement search entity

- error.go
- uiza.go
> Update handle error

- docs/Storage.md
- storage.go
- storage/client.go
https://dev.framgia.com/issues/222091
https://dev.framgia.com/issues/222093
> [#222087][Task][Storage][Add]: Add a storage

- docs/Entity.md
- entity.go
- entity/client.go
- entity/client_test.go
- mock/entity_mock.go
Gọi func Retrieve sau khi update thành công, để trả về all atribute của entity
[221745](https://dev.framgia.com/issues/221745)
> [#221743][#221745] - [Go][Entity][Update] Coding Document

- category.go
- category/client.go
- category/client_test.go
- docs/category.md
- mock/category_mock.go
- mock/entity_mock.go
- mock/mock.go
https://dev.framgia.com/issues/222068
https://dev.framgia.com/issues/222071
https://dev.framgia.com/issues/222074
https://dev.framgia.com/issues/222077
https://dev.framgia.com/issues/222080
https://dev.framgia.com/issues/222083
https://dev.framgia.com/issues/222086
https://dev.framgia.com/issues/222067
https://dev.framgia.com/issues/222070
https://dev.framgia.com/issues/222076
https://dev.framgia.com/issues/222079
https://dev.framgia.com/issues/222082
https://dev.framgia.com/issues/222085
> [#222068] - [Go][Category][Create] Document And Unit test

- docs/Storage.md
- mock/entity_mock.go
- mock/mock.go
- mock/storage_mock.go
- storage.go
- storage/client.go
- storage/client_test.go
https://dev.framgia.com/issues/222094
https://dev.framgia.com/issues/222095
https://dev.framgia.com/issues/222096
https://dev.framgia.com/issues/222097
https://dev.framgia.com/issues/222098
https://dev.framgia.com/issues/222100
https://dev.framgia.com/issues/222101
https://dev.framgia.com/issues/222102
> [#221791][Task][Storage]: Retrieve - Update - Remove a Storage

- category.go
- form/form.go
- uiza.go
- Rename Type to CategoryType for clearly convension
- Fix crash when using number in params
> Fix cannot use number params

- category/client_test.go
- mock/category_mock.go
https://dev.framgia.com/issues/222073
> [#222073] - [Go][Category][List] Unit test

- docs/Storage.md
https://dev.framgia.com/issues/222099
> [#222099][Task][Storage][Update] Document

- README.md
- category/client.go
- category/client_test.go
- client/client.go
- cmd/main.go
- docs/Storage.md
- entity/client_test.go
- iter.go
- mock/category_mock.go
- mock/entity_mock.go
- mock/storage_mock.go
- params.go
- storage/client.go
- storage/client_test.go
- testing/testing.go
- uiza.go
- Change package name to github.com/uizaio/api-wrapper-go
> Prepare for publish SDK

- entity/client.go
- Change package name to github.com/uizaio/api-wrapper-go
> Wrong package name

- README.md
- docs/ENTITY.md
> fix document

- docs/LIVE_STREAMING.md
- livestreaming.go
- livestreaming/client.go
- params.go
https://dev.framgia.com/issues/222112
https://dev.framgia.com/issues/222114
https://dev.framgia.com/issues/222116
> [222103][Task][Live streaming]: Create & Retrieve (Code + Doc)

- docs/LIVE_STREAMING.md
- livestreaming.go
- livestreaming/client.go
Redmine: 
https://dev.framgia.com/issues/222119
https://dev.framgia.com/issues/222121
> [222105] [Go] [Live streaming] Update Coding and document

- callback.go
- callback/client.go
- callback/client_test.go
- category/client_test.go
- docs/CALLBACK.md
- mock/callback_mock.go
- mock/mock.go
- params.go
- uiza.go
https://dev.framgia.com/issues/223747
https://dev.framgia.com/issues/223748
https://dev.framgia.com/issues/223749
https://dev.framgia.com/issues/223750
https://dev.framgia.com/issues/223752
https://dev.framgia.com/issues/223754
https://dev.framgia.com/issues/223755
https://dev.framgia.com/issues/223756
https://dev.framgia.com/issues/223757
https://dev.framgia.com/issues/223759
https://dev.framgia.com/issues/223760
https://dev.framgia.com/issues/223761
> [#223759] - Callback

- callback.go
- callback/client_test.go
- docs/CALLBACK.md
- entity/client_test.go
- mock/callback_mock.go
- mock/entity_mock.go
- mock/mock.go
- uiza.go
Refactor UnitTest :
* Increase Coverage
> Refactor UnitTest

- docs/LIVE_STREAMING.md
- live/client.go
- lives.go
https://dev.framgia.com/issues/222123
https://dev.framgia.com/issues/222125
https://dev.framgia.com/issues/222129
https://dev.framgia.com/issues/222131
https://dev.framgia.com/issues/222126
https://dev.framgia.com/issues/222128
> [222106#222107#222108][Task][Live streaming]: Start - Stop Feed & Get View

- entity.go
- entity/client_test.go
- mock/mock.go
update UT for Create and Retrieve Entity
> update UT: Create + Retrieve entity

- entity.go
- entity/client_test.go
- mock/entity_mock.go
- mock/mock.go
> Finish UT for Entity

- callback/client_test.go
- mock/callback_mock.go
- mock/mock.go
- mock/storage_mock.go
- storage/client_test.go
> UT storage

- docs/LIVE_STREAMING.md
- entity.go
- form/form.go
- live.go
- uiza.go
- implement json with array
- change argument inside param from *[]string to []*string
> [Phase 1][Sprint 4] Sending request application/json with slice

- analytic.go
- analytic/client.go
- analytic/client_test.go
- docs/ANALYTIC.md
- docs/CATEGORY.md
- docs/LIVE_STREAMING.md
- docs/STORAGE.md
- mock/analytic_mock.go
- params.go
https://dev.framgia.com/issues/222056
https://dev.framgia.com/issues/222053
https://dev.framgia.com/issues/222052
https://dev.framgia.com/issues/222058
https://dev.framgia.com/issues/222057
https://dev.framgia.com/issues/222054
> Analytic Get type and line

- docs/USER.md
- mock/user_mock.go
- params.go
- user.go
- user/client.go
- user/client_test.go
https://dev.framgia.com/issues/222026
https://dev.framgia.com/issues/222028
https://dev.framgia.com/issues/222029
https://dev.framgia.com/issues/222031
https://dev.framgia.com/issues/222032
https://dev.framgia.com/issues/222034
https://dev.framgia.com/issues/222035
https://dev.framgia.com/issues/222037
https://dev.framgia.com/issues/222038
https://dev.framgia.com/issues/222040
> [221796][Task][User]: Code & Document: Create - Retrieve - Update - List - Delete

- docs/CATEGORY.md
> Update docs category format

- form/form.go
> not convert empty param to url

- README.md
refactor readme call to uiza doc instead of doc in source
> [Phase 1][Sprint 4] Refactor readme call to uiza doc

- entity.go
- entity/client.go
- form/form.go
- params.go
- uiza.go
- Update Entity 
- Move AppID to BackEnd Config
> Update Entity and modify AppID

- entity.go
- uiza.go
- Fix error when using nil params 
- update Get AWS
> Fix error when using nil params

- category.go
- category/client.go
- category/client_test.go
- docs/CATEGORY.md
- mock/category_mock.go
- mock/mock.go
Redmine: https://dev.framgia.com/issues/228735
> [228716] Convert Category V3 => V4

- docs/STORAGE.md
- mock/storage_mock.go
- storage.go
- storage/client.go
- storage/client_test.go
Redmine: https://dev.framgia.com/issues/228745
> [228745] Convert Storage V3 => V4

- callback.go
- callback/client.go
- callback/client_test.go
- docs/CALLBACK.md
- mock/callback_mock.go
Redmine: https://dev.framgia.com/issues/228766
> [228766] Convert Callback V3 => V4

- entity.go
- live.go
- live/client.go
- live/client_test.go
- mock/live_mock.go
- mock/mock.go
- uiza.go
> Convert Live V3 to V4

- testing/testing.go
- uiza.go
> Update Entity UT

- docs/USER.md
- mock/mock.go
- mock/user_mock.go
- user.go
- user/client.go
- user/client_test.go
>  Convert User V3 to V4

- live.go
Fix bug lastPushInfo LiveData and LiveUpdateParams
> Fix bug LiveData and LiveUpdateParams

- entity.go
- live.go
Fix empty key of Entity / Live Update
> Fix empty key of Entity / Live Update

- entity.go
- live.go
- uiza.go
Hot fix and update version to 1.2.2
> Hot fix and update version to 1.2.2
